export const indianDestinations = [
  'Agra, Uttar Pradesh',
  'Ahmedabad, Gujarat',
  'Ajmer, Rajasthan',
  'Alappuzha, Kerala',
  'Alibaug, Maharashtra',
  'Almora, Uttarakhand',
  'Amritsar, Punjab',
  'Andaman Islands, Andaman and Nicobar',
  'Auli, Uttarakhand',
  'Aurangabad, Maharashtra',
  'Badami, Karnataka',
  'Badrinath, Uttarakhand',
  'Bandhavgarh, Madhya Pradesh',
  'Bangalore, Karnataka',
  'Bekal, Kerala',
  'Bharatpur, Rajasthan',
  'Bhimtal, Uttarakhand',
  'Bhopal, Madhya Pradesh',
  'Bhubaneswar, Odisha',
  'Bikaner, Rajasthan',
  'Bir Billing, Himachal Pradesh',
  'Bodh Gaya, Bihar',
  'Chandigarh, Chandigarh',
  'Chennai, Tamil Nadu',
  'Cherrapunji, Meghalaya',
  'Chikmagalur, Karnataka',
  'Coimbatore, Tamil Nadu',
  'Coorg, Karnataka',
  'Coonoor, Tamil Nadu',
  'Dalhousie, Himachal Pradesh',
  'Daman, Dadra and Nagar Haveli and Daman and Diu',
  'Darjeeling, West Bengal',
  'Dehradun, Uttarakhand',
  'Dharamshala, Himachal Pradesh',
  'Diu, Dadra and Nagar Haveli and Daman and Diu',
  'Dwarka, Gujarat',
  'Gangtok, Sikkim',
  'Gaya, Bihar',
  'Goa, Goa',
  'Gokarna, Karnataka',
  'Gulmarg, Jammu and Kashmir',
  'Guwahati, Assam',
  'Gwalior, Madhya Pradesh',
  'Hampi, Karnataka',
  'Haridwar, Uttarakhand',
  'Hyderabad, Telangana',
  'Imphal, Manipur',
  'Indore, Madhya Pradesh',
  'Itanagar, Arunachal Pradesh',
  'Jabalpur, Madhya Pradesh',
  'Jaipur, Rajasthan',
  'Jaisalmer, Rajasthan',
  'Jodhpur, Rajasthan',
  'Joshimath, Uttarakhand',
  'Kanchipuram, Tamil Nadu',
  'Kannur, Kerala',
  'Kanyakumari, Tamil Nadu',
  'Kargil, Ladakh',
  'Kasol, Himachal Pradesh',
  'Kasauli, Himachal Pradesh',
  'Kashid, Maharashtra',
  'Kaziranga, Assam',
  'Kedarnath, Uttarakhand',
  'Khajuraho, Madhya Pradesh',
  'Kochi, Kerala',
  'Kodaikanal, Tamil Nadu',
  'Kolkata, West Bengal',
  'Kovalam, Kerala',
  'Kufri, Himachal Pradesh',
  'Kumarakom, Kerala',
  'Kutch, Gujarat',
  'Lachung, Sikkim',
  'Leh, Ladakh',
  'Lonavala, Maharashtra',
  'Lucknow, Uttar Pradesh',
  'Mahabalipuram, Tamil Nadu',
  'Mahabaleshwar, Maharashtra',
  'Mandarmani, West Bengal',
  'Manali, Himachal Pradesh',
  'Mangalore, Karnataka',
  'Mount Abu, Rajasthan',
  'Mukteshwar, Uttarakhand',
  'Mumbai, Maharashtra',
  'Munnar, Kerala',
  'Mussoorie, Uttarakhand',
  'Mysore, Karnataka',
  'Nainital, Uttarakhand',
  'Nashik, Maharashtra',
  'Neil Island, Andaman and Nicobar',
  'Ooty, Tamil Nadu',
  'Orchha, Madhya Pradesh',
  'Pahalgam, Jammu and Kashmir',
  'Panchgani, Maharashtra',
  'Patnitop, Jammu and Kashmir',
  'Pelling, Sikkim',
  'Pondicherry, Puducherry',
  'Puri, Odisha',
  'Pushkar, Rajasthan',
  'Rameswaram, Tamil Nadu',
  'Ranikhet, Uttarakhand',
  'Ranthambore, Rajasthan',
  'Rishikesh, Uttarakhand',
  'Shimla, Himachal Pradesh',
  'Shillong, Meghalaya',
  'Spiti Valley, Himachal Pradesh',
  'Srinagar, Jammu and Kashmir',
  'Tawang, Arunachal Pradesh',
  'Thekkady, Kerala',
  'Tirupati, Andhra Pradesh',
  'Trivandrum, Kerala',
  'Udaipur, Rajasthan',
  'Ujjain, Madhya Pradesh',
  'Varanasi, Uttar Pradesh',
  'Varkala, Kerala',
  'Visakhapatnam, Andhra Pradesh',
  'Wayanad, Kerala',
  'Ziro Valley, Arunachal Pradesh'
];
