const BASE_GATEWAY = 'http://localhost:5050';

module.exports = {
  GATEWAY: BASE_GATEWAY,
  AUTH: BASE_GATEWAY,
  BOOKING: BASE_GATEWAY,
  POST: BASE_GATEWAY,
  AI: BASE_GATEWAY,
  UPLOAD: BASE_GATEWAY,
  CHAT: BASE_GATEWAY,
  ADMIN: BASE_GATEWAY,
  NOTIFICATION: BASE_GATEWAY,
  MATCHES: BASE_GATEWAY,
  SOCIAL: BASE_GATEWAY,
};
